spring:
  main:
    banner-mode: off
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
  flyway:
    enable: true
    cleanOnValidationError: true
    cleanDisabled: false
    locations: classpath:db/migration

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    com.zaxxer.hikari.pool: ERROR